<?php
App::uses('View','View');
App::uses('CakeTcpdf', 'Tcpdf.Lib');
 
class PdfView extends View {
	
	/**
	 * @var CakeTcpdf
	 */
	protected $_tcpdf;
	
	protected $_config = array(
		'download' => false,
		'filename' => '', // Will be autogenerated from url, if empty
		'raw' => false,
	);
	
	public function __construct(Controller $controller = null) {
		
		parent::__construct($controller);
		
		$this->response->type('pdf');
		
		if ($this->layoutPath === null) {
			$this->layoutPath = 'pdf';
		}
		
		if ($this->request->query('download')) {
			$this->_config['download'] = true;
		}
		
		if ($this->request->query('raw')) {
			$this->_config['raw'] = true;
		}
		
		// autoload PdfHelper
		if (!array_key_exists('Tcpdf.Pdf', $this->helpers) && !in_array('Tcpdf.Pdf', $this->helpers)) {
			$this->helpers[] = 'Tcpdf.Pdf';
		}
	}
	
	public function &tcpdf() {
		if (!$this->_tcpdf) {
			//TODO Use dependency injection
			$pdf = new CakeTcpdf();
			$pdf->setupDefaults();
			$this->_tcpdf = $pdf;
		}
		return $this->_tcpdf;
	}
	
	public function render($view = null, $layout = null) {
		
		// read config from view vars
		$config = $this->_config;
		if ($this->get('pdf')) {
			$config = am($config, $this->get('pdf'));
		}
		
		$pdf =& $this->tcpdf();
		
		$content = parent::render($view, $layout);
		
		//if ($pdf->rendered === true) {
			//debug('already rendered');
		//}
		//else {
		//}
		$pdf->writeHTML($content, true, 0, true, 0);
		//debug('rendered');
		
		$outputType = 'I';
		if ($config['download']) {
			$outputType = 'D';
		}
		elseif ($config['raw']) {
			$outputType = 'S';
			$this->response->type('text');
		}
		
		$filename = ($config['filename']) 
			? ($config['filename']) 
			: Inflector::slug($this->request->url,'_').'.pdf';
		
		$pdfBuffer = $pdf->Output($filename,$outputType);
		
		return $pdfBuffer;
	}
	
}
?>